repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=100']
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/PyCQA/isort
  rev: 5.9.1
  hooks:
    - id: isort
      name: isort (python)
      args: ['--profile', 'black', '--filter-files']

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy
      pass_filenames: false
      args: ['probeye', '--ignore-missing-imports']

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      args: [
          '--max-line-length=88',
          '--select=E,F,W,C90,B,I',
          '--ignore=E203,W503',
          '--import-order-style=pycharm',
          '--application-import-names=probeye, tests'
      ]
      additional_dependencies: [
          flake8-bugbear,
          flake8-tidy-imports,
          flake8-import-order
      ]